version: 2

models:
    -   name: 
        description: 
        columns: 
            -   name: 
                description: "primary key"
                data_tests:
                    - unique
                    - not_null